[scripts/ci.baseline.txt] Fix incorrect entries [bde] Add some platform support (#39119)
Fix incorrect entries of `scripts/ci.baseline.txt`.

Fix #38787, won't fix downstream `rmqcpp` for #38736.

* Keep skip in CI
  -  Conflict dependencies `pcre2`, `ryu` in #32645
* Disable `android`
- There is a weird error that failed to find
`BdeBuildSystem/bbs_runtest.py` by
`BdeBuildSystem/BdeBuildSystemConfig.cmake`
* Disable `arm64-windows`
- Failed with `groups\bsl\bsls\bsls_platform.h(419): fatal error C1189:
#error: "Unable to identify CPU on which the MSVC compiler is running."`
* Disable `uwp`
- Failed with `groups\bdl\bdlb\bdlb_randomdevice.cpp(93): error C3861:
'CryptAcquireContext': identifier not found`
* Check `scripts/ci.baseline.txt`
- Checked by `Get-Content ./scripts/ci.baseline.txt | Select-String
-NotMatch '^#' | Select-String -NotMatch
':(arm-neon-android|arm64-android|arm64-osx|arm64-uwp|arm64-windows|x64-android|x64-linux|x64-osx|x64-uwp|x64-windows|x64-windows-static|x64-windows-static-md|x86-windows)\s*='`