CI Fixes from 2021-06-26 (#18664)
* CI Fixes from 2021-06-26

https://dev.azure.com/vcpkg/public/_build/results?buildId=55364&view=logs&j=0a61404f-5c45-5632-e83c-408b7fcca1d6&t=59cc5a87-398a-597b-cb3d-5842723775f1

PASSING, REMOVE FROM FAIL LIST: aubio:arm64-windows (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: aubio:x64-windows (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: aubio:x86-windows (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: caf:arm64-windows (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: chartdir:x64-linux (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: coolprop:x64-linux (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: fdk-aac:arm-uwp (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: fdk-aac:arm64-windows (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: fdk-aac:x64-uwp (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: fontconfig:x64-windows-static-md (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: google-cloud-cpp:arm64-windows (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: gtkmm:x64-linux (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: libmagic:x64-windows-static (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: libmagic:x64-windows-static-md (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: libopusenc:x64-linux (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: lua:arm-uwp (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: lua:x64-uwp (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: matio:x64-linux (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: offscale-libetcd-cpp:arm64-windows (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: proj4:arm64-windows (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: z3:arm64-windows (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: zeromq:arm64-windows (.\scripts\ci.baseline.txt)

:)

REGRESSION: clipp:x86-windows. If expected, add clipp:x86-windows=fail to .\scripts\ci.baseline.txt.

>[DEBUG] Downloading https://vcpkgteststorage.blob.core.windows.net/osxpr20201017/4645fafe85a8099ea97b85e939747a12e9b3b92213b5b8207a9c277537377b77b5daebd88a4c090ea89cfff2937a9fc155da6e8b5558574d7129227c28826e1c?sv=2019-12-12&ss=b&srt=sco&sp=rwlac&se=2021-06-01T19:00:00Z&st=2021-02-02T21:14:48Z&spr=https&sig=5OqlHLAKxxH9%2F2G%2BwO4ngXiG%2Bd0ASB81PklNDOIAUUk%3D
>[DEBUG] Downloading https://github.com/muellan/clipp/archive/2c32b2f1f7cc530b1ec1f62c92f698643bb368db.tar.gz
>Error: Failed to download from mirror set:
>https://vcpkgteststorage.blob.core.windows.net/osxpr20201017/4645fafe85a8099ea97b85e939747a12e9b3b92213b5b8207a9c277537377b77b5daebd88a4c090ea89cfff2937a9fc155da6e8b5558574d7129227c28826e1c?sv=2019-12-12&ss=b&srt=sco&sp=rwlac&se=2021-06-01T19:00:00Z&st=2021-02-02T21:14:48Z&spr=https&sig=5OqlHLAKxxH9%2F2G%2BwO4ngXiG%2Bd0ASB81PklNDOIAUUk%3D: failed: status code 403
>https://github.com/muellan/clipp/archive/2c32b2f1f7cc530b1ec1f62c92f698643bb368db.tar.gz: failed: status code 502
>[DEBUG] C:\A\1\14\s\src\vcpkg\base\downloads.cpp(652)

Looks like a transient download failure. Might be something funky with artifact caching.

REGRESSION: liblas:arm64-windows. If expected, add liblas:arm64-windows=fail to .\scripts\ci.baseline.txt.

>fatal error C1189: #error:  The file liblas/detail/endian.hpp needs to be set up for your CPU type.

Probably was blocked by one of the many "passing" libs on arm64-windows. Skipped.

REGRESSION: libsbml:x64-windows-static. If expected, add libsbml:x64-windows-static=fail to .\scripts\ci.baseline.txt.

>[DEBUG] Downloading https://vcpkgteststorage.blob.core.windows.net/osxpr20201017/49dedaa2fcd2077e7389a8f940adf931d80aa7a8f9d57330328372d2ac8ebcaeb03a20524df2fe0f1c6933587904613754585076c46e6cb5d6f7a001f427185b?sv=2019-12-12&ss=b&srt=sco&sp=rwlac&se=2021-06-01T19:00:00Z&st=2021-02-02T21:14:48Z&spr=https&sig=5OqlHLAKxxH9%2F2G%2BwO4ngXiG%2Bd0ASB81PklNDOIAUUk%3D
>[DEBUG] Downloading https://sourceforge.net/projects/sbml/files/libsbml/5.18.0/stable/libSBML-5.18.0-core-plus-packages-src.tar.gz/download
>Error: Failed to download from mirror set:
>https://vcpkgteststorage.blob.core.windows.net/osxpr20201017/49dedaa2fcd2077e7389a8f940adf931d80aa7a8f9d57330328372d2ac8ebcaeb03a20524df2fe0f1c6933587904613754585076c46e6cb5d6f7a001f427185b?sv=2019-12-12&ss=b&srt=sco&sp=rwlac&se=2021-06-01T19:00:00Z&st=2021-02-02T21:14:48Z&spr=https&sig=5OqlHLAKxxH9%2F2G%2BwO4ngXiG%2Bd0ASB81PklNDOIAUUk%3D: failed: status code 403
>https://sourceforge.net/projects/sbml/files/libsbml/5.18.0/stable/libSBML-5.18.0-core-plus-packages-src.tar.gz/download: WinHttpReceiveResponse() failed: 12175
>
>[DEBUG] C:\A\1\14\s\src\vcpkg\base\downloads.cpp(652)
>[DEBUG] Exiting after 548953 us (542540 us)

Looks like a transient download failure. But 403 forbidden looks like artifact caching failure...

REGRESSION: luafilesystem:arm-uwp. If expected, add luafilesystem:arm-uwp=fail to .\scripts\ci.baseline.txt.
REGRESSION: luafilesystem:x64-uwp. If expected, add luafilesystem:x64-uwp=fail to .\scripts\ci.baseline.txt.
REGRESSION: luasocket:arm-uwp. If expected, add luasocket:arm-uwp=fail to .\scripts\ci.baseline.txt.
REGRESSION: luasocket:x64-uwp. If expected, add luasocket:x64-uwp=fail to .\scripts\ci.baseline.txt.

Were previously blocked by lua, marked as 'fail'.

REGRESSION: vcpkg-find-acquire-program:arm-uwp. If expected, add vcpkg-find-acquire-program:arm-uwp=fail to .\scripts\ci.baseline.txt.
REGRESSION: vcpkg-find-acquire-program:x64-windows-static. If expected, add vcpkg-find-acquire-program:x64-windows-static=fail to .\scripts\ci.baseline.txt.
REGRESSION: vcpkg-find-acquire-program:x64-windows. If expected, add vcpkg-find-acquire-program:x64-windows=fail to .\scripts\ci.baseline.txt.

These are almost certainly the same artifact caching transient.

* Aubio typo.