[ffmpeg] fixed build on Windows ARM (#27295)
* [ffmpeg] fixed build on Windows ARM

Currently build fails with the error:
```
Building ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:arm64-windows...
-- Using cached ffmpeg-ffmpeg-n4.4.1.tar.gz.
-- Cleaning sources at C:/projects/synfig-arm/vcpkg/buildtrees/ffmpeg/src/n4.4.1-9dd22c1484.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/projects/synfig-arm/vcpkg/downloads/ffmpeg-ffmpeg-n4.4.1.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
...
-- Downloading https://repo.msys2.org/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz;https://mirror.bit.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz;https://mirror.selfnet.de/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz -> msys-gmp-6.2.0-1-x86_64.pkg.tar.xz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://repo.msys2.org/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz
[DEBUG] Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz
[DEBUG] Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz
[DEBUG] Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz
[DEBUG] Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz
[DEBUG] Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
[DEBUG] Downloading https://mirror.selfnet.de/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz
[DEBUG] Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
Error: Failed to download from mirror set:
https://repo.msys2.org/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: failed: status code 404
https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: failed: status code 404
https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: failed: status code 404
https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: failed: status code 404
https://mirrors.ustc.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: failed: status code 404
https://mirror.bit.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: WinHttpSendRequest() failed: 12007
https://mirror.selfnet.de/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: failed: status code 404
https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: WinHttpSendRequest() failed: 12029
https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: WinHttpSendRequest() failed: 12029
https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: WinHttpSendRequest() failed: 12029
https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz: WinHttpSendRequest() failed: 12029
```

This happens because MSYS2 has switched to zstd compression and
`https://repo.msys2.org/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz`
already removed from the MSYS2 repository.

Also I bumped other dependencies too.

* [ffmpeg] bump port-version